### ISSUE TITLE
Add option for array syntax in flattened property names with "extra dot" before the index bracket

### ISSUE THREAD

**Issue by Eric24** [Nikaple/uni-flatten#95]
## I'm submitting a...

- [ ] Regression 
- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Support request

## Current behavior

An array index is inserted into the flatted property name like this (without a `.` between the `c` and the `[3]`): `'a.b.c[3].xyz'`

## Expected behavior

Ideally, the flatten function would have the option to produce this syntax (with a `.`): `'a.b.c.[3].xyz'`

## What is the motivation / use case for changing the behavior?

Various libraries use either or both syntaxes when it comes to expressing paths into JavaScript objects. Unfortunately, there is no universal standard, but it would be very convenient to be able to choose the desired syntax in cases where uni-flatten is being used along with other libraries that prefer or require the "extra dot" syntax.

I've tested the unflatten function, and it already seamlessly supports the syntax with the "extra dot", so only the flatten function would change.

PS - I've done extensive testing with various flatten/unflatten libraries, and this is by far the most complete. Great job!

**Comment by Nikaple** [comment]
I have opened a pull request for this feature. Please refer to [this test](https://github.com/Nikaple/uni-flatten/pull/96/files#diff-03b774e0cf4764a62a7fd9e605240ecdf7c39a774fc5290c345f2591fc64c375R206). Does it look okay to you?

**Comment by Eric24** [comment]
Thank you for the quick response! That looks great and fully satisfies my use-case.

Note that the custom serializer has pros and cons (as you've already mentioned). On one hand, it's highly flexible, but it can also break the deserializer (my particular syntax doesn't break it, but it's only one case). What I might suggest is that you consider the option for a custom deserializer too. It's not something I have a specific use-case for today, but it would provide the option for someone to define an entirely different serialization syntax, and mostly, it will "complement" the ability to set a customer serializer.

**Comment by Eric24** [comment]
Understood. Thank you!
